version: 2
jobs:
  test:
    docker:
    - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      name: ci-pg-locationservice
      environment:
        TRANSIENT: false 
        POSTGRES__CSTR: Host=localhost;Username=integrator;Password=inteword;Database=locationservice;Port=5432
    - image: circleci/postgres:11.4-alpine-ram
      environment:
        POSTGRES_USER: integrator
        POSTGRES_PASSWORD: inteword
        POSTGRES_DB: locationservice
    steps:
    - checkout
    - run: 
        name: Apply Migrations
        command: dotnet ef database update --project src/StatlerWaldorfCorp.LocationService/StatlerWaldorfCorp.LocationService.csproj
    - run: dotnet restore
    - run: dotnet build --no-restore
    - run:
        name: Test App
        command: dotnet test --no-build

  docker-push:
    machine: true
    steps:
    - checkout
    # build and push Docker image
    - run: 
        name: Push to docker hub
        command: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t   mad0314/locationservice:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (4)
          docker push mad0314/locationservice:$TAG


workflows:
  version: 2
  workflow:
    jobs:
    - test
    - docker-push:
        requires:
        - test

